### PR TITLE
add zig to langs_to_asm

### PR DESCRIPTION
**Pull request by dankeyy**

### CODE REVIEW

**Comment by cmuratori** [comment]
I could not figure out how to select "Zig" from Compiler Explorer normally. Do we need to add extra instructions to explain how to do that? Unless I'm messing something up, I could only do it if I went to zig.godbolt.org explicitly... so if that's the case, we should add a "*" to the zig table entry that explains you have to go to a different URL.

\- Casey

**Comment by dankeyy** [comment]
Works fine here image

**Comment by cmuratori** [comment]
OK now I am truly confused. If I open a private browsing window, just to make sure there's no weird cookie stuff going on, I do not get a "Zig" listed in the drop-down list. I tried both Brave, Edge, and Chrome, no luck.

However, if I _type_ Zig into the box, rather than try to pick it from the menu, _it accepts it_. Can you double-check and confirm that Zig actually shows up in your _menu_, not just when you type it in?

\- Casey

**Comment by cmuratori** [comment]
Just to confirm, I went and looked at the source to the godbolt page, and Zig _definitely is not included_ in the source for that drop-down. I wonder if this is a mistake that should be reported to godbolt?

\- Casey

**Comment by dankeyy** [comment]
Oh yea, definitely only works when you type it in
I do think it should be reported to godbolt, yea

**Comment by mmozeiko** [comment]
They have a bug there. The combo-box widget they use do max 50 items by default. But the language list is 55 items.
If you open JS console (`ctrl+shift+J` in chrome) and do `$("#tomselect-1").tomselect.settings.maxOptions=100;` then the combo-box will show all the items. Otherwise it cuts all languages above 50 item limit.

You can see that similar combo-box used for compiler version selection (gcc vX, clang vX, msvc vX) has explicitly set very high limit to show all the items: [$("#tomselect-1").tomselect.settings.maxOptions=100;](https://github.com/compiler-explorer/compiler-explorer/blob/55dc09017e672ec9705fd11746f48d1de98b443f/static/widgets/compiler-picker.ts#L120)

**Comment by mmozeiko** [comment]
The drop-down is now fixed on godbolt.org, you can see there all the languages.

**Comment by cmuratori** [comment]
Roger that - I have removed the note.

\- Casey

**Pull request merged**
