### PR TITLE
Add contrib_webassembly

### PR DESCRIPTION
**Pull request by gautam1168**

### CODE REVIEW

**Comment by gautam1168** [comment]
Hey thanks @mmozeiko . I didn't know this pr was already made! I am still making changes to this. I will go over your comments in a minute.

**Comment by gautam1168** [comment]
@mmozeiko
The reason I am writing the things byte by byte is because I want to write the items in a sequence that is easy for me to read off using typed arrays on  the javascript side. For example when Im writing the instruction_table if the Encodings come first then using Uint32Array it will be difficult for me to tell where the Encodings end and the number of encodings is. 

The sim8086_text was in an intermediate stage at that point. Please take a look at it again. Now I have reused most of it from the root directory, and only changed the things that require a fprintf.

 I really wanted to give people the .wasm file so that they don't have to build it. Building it requires that they have an updated version of clang installed and I wouldn't expect everyone trying this exercise with javascript to have that available. Can I really not just provide it there? If not I can provide it on my repo and just link it in the readme. 

For PrintToOutput, I need to be able to transfer strings as arrays of bytes to javascript side. Only then I can use String.fromCharCode on the javascript side to pass the string to v8 functions that take strings. I need to transfer a byte array any time I need to transfer over a string. And that means I have to do it through some global shared memory. However, for the functions in lib.js which are the wrapper functions exposed in the library I do return plain strings that people can use normally. `LoadLibrary`  returns these functions:
```
Sim86_GetVersion,
    Sim86_Decode8086Instruction,
    Sim86_RegisterNameFromOperand,
    Sim86_MnemonicFromOperationType,
    Sim86_Get8086InstructionTable
```
And these behave exactly like you want I think. Please look at how these behave: https://pasteboard.co/j4aDT8pE6Ou3.png
I have split these out into the lib.js which I am giving as the javascript wrapper. The main.js file is really for verifying that the challenge listing works with this and for people who might want to use wasm directly.

I will change the assert function to use a builtin as you said and also use the set method.

**Comment by mmozeiko** [comment]
> The reason I am writing the things byte by byte is because I want to write the items in a sequence that is easy for me to read off using typed arrays on the javascript side. 

Well, it's your choice, but this is strange way to write wrappers. Good wrappers read typed arrays off wasm heap without global variables for output. Like if you have function in wasm land that does `void GetFoo(Foo* foo) { ... }` that writes to *foo, then you can simply pass pointer to wasm memory from JS (`GetFoo(ptr)`), and when it returns, you access this wasm memory directly to read bytes or words or whatever from `ptr`. No need to to copy it to global variable first, and then read it back. It's way less code to maintain.

Ideally you want to have exactly 0 copies of things you put into wasm or out of wasm. Nobody likes to maintain wrapper data structures multiple times. Nicer JS objects to use is fine - then data should be converted to JS, but making copy through global variable is not a nice way to do that.

> For PrintToOutput, I need to be able to transfer strings as arrays of bytes to javascript side. Only then I can use String.fromCharCode on the javascript side to pass the string to v8 functions that take strings. I need to transfer a byte array any time I need to transfer over a string. And that means I have to do it through some global shared memory.

But you don't need to transfer them as array of bytes separately through global variable. You can directly return pointer that is converted to string. That's my point.
Like if you have function in wasm that does `const char* GetHello() { return "hello"; }` Then you can call in JS directly: `const ptr = exports.GetHello();` And then if you want return string, you do the string: `const str = String.fromCharCode.apply(null, mem8.slice(ptr, mem8.indexOf(0, ptr))));` where `mem8 = new Uint8Array(wasmMemory.buffer);` Everything else is just useless overhead.

> I really wanted to give people the .wasm file so that they don't have to build it. 

The repository size will be terrible if all wrappers (node.js, go, C#, Python, etc...) will start putting their build/binary files in repo. Especially if things will change later - adding newer API, more instructions, bugfixes, etc...

**Comment by gautam1168** [comment]
Closed it by mistake. I will make some updates today @mmozeiko. Although I will probably need to talk to you a little bit more about the global variable issue here. I don't think I'm really duplicating the memory here. The `PrintToOutput` is simply replacing the lack of a stdout and fprintf by allocating a bunch of memory and using it as such. The wasm memory layout I have used is like this
```
---------1 << 20 bytes----------------|--------------output memory instead of stdout/stderr---------|
```

So the things I'm writing in `PrintToOutput` go to the memory after the 1MB that is used by the simulator. I don't really quite understand what you mean by global variable here. It is just reading the things out of there like you say. The javascript side is just getting pointers to the second part in the memory above and is reading things off of it.

I will see if I can catch you on discord today sometime so I can chat with you about this. Thankyou for looking through my PR. I will make some changes today.

I will remove the wasm binary and put a link in the readme.

**Comment by gautam1168** [comment]
@mmozeiko can you please accept my friend request on discord? My username is `gautam1168`. I understand if you would rather not be disturbed by DMs but I think I'll be able to explain myself better in realtime.

**Comment by cmuratori** [comment]
Please respect people's privacy and do not ask them to friend/DM/follow/etc. on various services... especially Martins, who answers 99% of the questions posted on the internet. If he had personal conversations with everyone he advises, he would never sleep :)

\- Casey

**Comment by mmozeiko** [comment]
I have my DM's open on Discord, there is no need for any friend requests. If you cannot send messages, that is up to your discord configuration ("allow messages from others server members" or whatever it is called).

> I don't really quite understand what you mean by global variable here.

I mean that instead of this:
```
  function Sim86_MnemonicFromOperationType(Type) {
    const Length = instance.exports.Sim86_MnemonicFromOperationTypeWasm(
      Type, instance.exports.__heap_base, MaxMemory
    )   
    const resultBytes = view.slice(instance.exports.__heap_base + (1 << 20));
    const result = String.fromCharCode.apply(null, resultBytes.slice(0, Length));	
    return result;
  }
```

you should do this:
```
  function Sim86_MnemonicFromOperationType(Type) {
    const ptr = instance.exports.Sim86_MnemonicFromOperationTypeWasm(Type);
    const mem8 = new Uint8Array(instance.memory.buffer); // this can be stored globally - in same place where "instance" is
    return String.fromCharCode.apply(null, mem8.slice(ptr, mem8.indexOf(0, ptr)));
  }
```

And function in C does not need any wrapper - it can use original C function from sim86_lib.cpp that returns `const char*` as is.  No changes needed.

Similar with other functions. No PrintToOutput needed.

**Comment by gautam1168** [comment]
@mmozeiko oh I see. That is fine, I can return the pointer from the function. I'll make the update. If I understand correctly, you are saying I shouldn't use a hardcoded offset like that in the shared memory to figure out where the output is, and instead use a pointer returned from the function. However, the printToOutput function will still be the same. I will update the code. Just in a couple hours. Thankyou again for all the help you provide and the infinite patience you seem to have.

I honestly did not realize that asking for the discord thing could be a privacy issue. I will also change my settings. As @cmuratori said, you really are phenomenally helpful and I wouldn't want to create any trouble for you.

**Comment by gautam1168** [comment]
I have added the modification and now the assert works. It can be triggered by `window.clib.TriggerTrap()`

**Comment by mmozeiko** [comment]
I'm very confused why you want PrintToOutput your strings. You can simply return GetRegName() and GetMnemonic() result from C functions. And then use the wasm pointer in JS to get JS string.

In my opinion the Sim86_MnemonicFromOperationTypeWasm function should be exactly same as original Sim86_MnemonicFromOperationType:
```
extern "C" char const *Sim86_MnemonicFromOperationType(operation_type Type)
{
    char const *Result = GetMnemonic(Type);
    return Result;
}
```
No changes needed.

And then in JS you do:
```
  function Sim86_MnemonicFromOperationType(Type) {
    const resultOffset = instance.exports.Sim86_MnemonicFromOperationType(Type);
    return String.fromCharCode.apply(null, view.slice(resultOffset, view.indexOf(0, resultOffset)));
  }
```

Same for Sim86_RegisterNameFromOperand. All that heap memory management can go completely away, except in cases when passing byte array in for dissassembly - then you need to copy those bytes in.

**Comment by gautam1168** [comment]
Ah I see. I have two reasons for that:
1. I want the javascript side to only read from the part of memory that is outside the 1MB limit of the simulator. All the `PrintToOutput` is doing is moving the things I want the javascript side to read, to right outside that 1MB limit.
2. I was afraid that the char * that was being returned from `GetMnemonic` for example, was on the stack and not the heap and it will evaporate by the time I got around to reading it in my javascript. 

Now this is a noob question but Im looking at the `GetRegName` function in `perfaware/sim86/sim86_text.cpp` and I see that the register names are being created inside the function without doing a malloc or using the segmented_access. So I would expect that to be on the stack. And then I would expect that any pointers that are returned to those items on the stack will become invalid after the function exits.... This had happened to me in handmade hero once and so I avoid it whenever possible. And that is why I am making absolutely sure that I know where I am writing those strings onto the heap and then passing out a pointer to that.

However, I will try the way you pointed it out above today. And Ill update my PR if it works.... I don't see how it can work but Ill try.

**Comment by gautam1168** [comment]
I have learned new things about string literals. Walter Plinge said that the literals will be inside the exe in that file... which is blowing my mind right now. But if the exe is what is there in the memory before the `__heap_base` then this could work. Let me try in a couple hours.

**Comment by gautam1168** [comment]
My first attempt to just use the pointer returned by the `GetMnemonic` didn't really work. It returns a wrong result. I may be doing something wrong though:
image

I will try to track down what is happening there.

**Comment by mmozeiko** [comment]
String literal lifetime is global. That is defined by C standard. So any time you have pointers to string literals, they will stay valid through the lifetime of your program (or more precisely exe/dll where they are compiled in).

So code like this:
```
const char* GetFoo() {
  const char* ptr = "foo";
  return ptr;
}
```
is completely valid.
You may be confusing them with local char arrays:
```
const char* GetFoo() {
  const char ptr[] = "foo"; // initializes 4 byte long array on stack
  return ptr; // bad
}
```
this is not good - as it is returning pointer to local stack frame.

In native code string literals typically are implemented by placing them in global data section. Which is loaded on exe/dll startup by OS and stay loaded.

In wasm there is only one big memory runtime can use. So wasm places all of global initialized data in beginning of this memory. That's why there is such __heap_base offset, which you can use for "heap". Why do you think it exists at all and is not always 0? Because from 0 to __heap_base complier & wasm runtime stores the global data. You can print those bytes out and check what's there - all your string constants will be from that area.

That's why any pointer returned to JS can be read from wasm instance.memory.buffer array. Regardless is it a global string literal, or "heap" allocated.

**Comment by gautam1168** [comment]
This makes so much sense. I will update my code. I never understood why that __heap_base thing was there.

**Comment by gautam1168** [comment]
@mmozeiko I have made the changes to be able to read the pointers directly from the program memory without copying it to output memory first. I also modified the `Sim86_Get8086InstructionTableWasm` to directly write to the destination instead of manually writing the bytes.

**Comment by gautam1168** [comment]
@mmozeiko I made a custom `fprintf` using some macros to make the FILE type my own and also by using a global variable. With this I do not need to duplicate any of the functions in `sim86_text.cpp`. Should I update this PR to have it use the custom `fprintf`? I think it will be less maintenance if I do it this way but I'm not putting it in the PR before asking you since you have already seen the code on this branch and I don't want to change it so much without letting you know. 
https://github.com/gautam1168/computer_enhance/blob/customfprintf/perfaware/sim86/shared/contrib_webassembly/sim86_text.cpp

**Comment by mmozeiko** [comment]
Now the sim8086.cpp looks much simpler! I'd consider including sim86_lib.cpp in there to avoid code duplication - all of the functions you wrote are already in `sim86_lib.cpp` file. Just need tiny `#ifndef __wasm__` around any #include not needed, and that's it. Then your wasm library be created exactly from same source code as C++ native code or any other contributed wrapper.

Not sure why you want to put `Entry` in there, as that is not part of library. That sounds like you're creating application that uses your wasm code... and is not a wrapper. If you ask me for my opinion, I would create it as separate "test.wasm" file to load and call, not part of main wasm module to give to others - which should be just a library. Look at how other language wrappers are offering this functionality. The same thing about sim86_text.cpp - that's not part of shared library wrapper - see the `sim86_shared.h` file that lists functionality needed for such wrappers.

**Comment by gautam1168** [comment]
@mmozeiko I have split out the test code into `sim8086_test.cpp` which includes the `Entry`. I had to still include the custom definition of `fprintf` in my library bundle because otherwise including `sim86_lib.cpp` doesn't compile. But now the `contrib_webassembly/sim8086.cpp` has just 3 includes and no code.

**Comment by gautam1168** [comment]
The wrapper works. I used it for this: https://gautam1168.github.io/Part5-8086/index.html
image

**Comment by gautam1168** [comment]
@mmozeiko I also made another example for execution using the wasm bindings directly. Meaning wrote the c++ code in sim8086-test.cpp of my contrib folder and compiled it. That also works: https://gautam1168.github.io/Part5-8086/pure_wasm/index.html

**Comment by gautam1168** [comment]
Thankyou @cmuratori :)

**Pull request merged**
