### PR TITLE
Add a Zig "wrapper"

### PR DESCRIPTION
**Pull request by penguingovernor**
Hi Casey!

Just wanted to say that I'm enjoying the class so far!  I'm really learning a ton! :)

I added a [Zig](https://ziglang.org/) wrapper for your 8086 library code! In order to do so I had to slightly modify the existing `sim86_shared.h` file so that it could be compatible with both a C/C++ compiler. I don't think it should break anything as the following command still works for me: `clang++ shared_library_test.cpp ../sim86_lib.cpp`

The reason for C/C++ header compatibility is that this PR actually leverages Zig's C/C++ compiling capabilities to build your library (ie no precompiled libraries are used at all) from scratch and build minimal wrapper around the exported function to be Zig-like. 

(if you take a look at sim86.zig you'll see that there's very little code and it's really just calling out to the c environment)

This allows users of this Zig library to cross compile or even clone your repo as a submodule and use the library as if it was a native Zig one. 

Let me know what you think, cheers!

### CODE REVIEW

**Comment by cmuratori** [comment]
Yes, that's no problem. I considered doing that myself when I posted it originally, actually, because I wasn't sure if anyone out there would want to use it in vanilla C. So this would also enabled that usage.

I don't have time right now to test the shared.h change, but as soon as I do I'll merge the request.

Thanks,
\- Casey

**Comment by mmozeiko** [comment]
I'm surprised `typedef struct X : u32 { .. } X;` thing. In C you cannot have enums selecting underlying type, is zig C import allows such C++isms?

Also the bottom of file I would suggest to do this instead:
```
#ifdef __cplusplus
extern "C" {
#endif
...
#ifdef __cplusplus
}
#endif
```
Then there won't be need to duplicate function declarations.

**Comment by mmozeiko** [comment]
> Also declaring an underlying-type for an enum should be in [C23 standard](https://en.cppreference.com/w/c/language/enum).

Ah, that explains it. Thanks!

**Comment by cmuratori** [comment]
Just wanted to double-check after the discussion here: is the current state of the pull request still the one I should look at to merge, or are there still changes being made?

\- Casey

**Comment by penguingovernor** [comment]
I think I've addressed all the requested changes; it should be good to go. (:

**Comment by cmuratori** [comment]
OK then I'm going to merge this and then I might want to edit the modified .h file, so you'll have to watch for that and tell me if it breaks any Zig things if/when I do.

\- Casey

**Comment by penguingovernor** [comment]
> OK then I'm going to merge this and then I might want to edit the modified .h file, so you'll have to watch for that and tell me if it breaks any Zig things if/when I do.
> 
> - Casey

Will do! Thanks for merging this.

**Pull request merged**
